<?php

return array(
    'SegmentPlugin_AttributeConditionCheckbox' => $base . '/SegmentPlugin/AttributeConditionCheckbox.php',
    'SegmentPlugin_AttributeConditionCheckboxgroup' => $base . '/SegmentPlugin/AttributeConditionCheckboxgroup.php',
    'SegmentPlugin_AttributeConditionDate' => $base . '/SegmentPlugin/AttributeConditionDate.php',
    'SegmentPlugin_AttributeConditionSelect' => $base . '/SegmentPlugin/AttributeConditionSelect.php',
    'SegmentPlugin_AttributeConditionText' => $base . '/SegmentPlugin/AttributeConditionText.php',
    'SegmentPlugin_Condition' => $base . '/SegmentPlugin/Condition.php',
    'SegmentPlugin_ConditionException' => $base . '/SegmentPlugin/ConditionException.php',
    'SegmentPlugin_ConditionFactory' => $base . '/SegmentPlugin/ConditionFactory.php',
    'SegmentPlugin_DAO' => $base . '/SegmentPlugin/DAO.php',
    'SegmentPlugin_DateConditionBase' => $base . '/SegmentPlugin/DateConditionBase.php',
    'SegmentPlugin_NoConditionsException' => $base . '/SegmentPlugin/NoConditionsException.php',
    'SegmentPlugin_Operator' => $base . '/SegmentPlugin/Operator.php',
    'SegmentPlugin_SavedSegments' => $base . '/SegmentPlugin/SavedSegments.php',
    'SegmentPlugin_SubscriberConditionActivity' => $base . '/SegmentPlugin/SubscriberConditionActivity.php',
    'SegmentPlugin_SubscriberConditionEmail' => $base . '/SegmentPlugin/SubscriberConditionEmail.php',
    'SegmentPlugin_SubscriberConditionEntered' => $base . '/SegmentPlugin/SubscriberConditionEntered.php',
    'SegmentPlugin_SubscriberConditionIdentity' => $base . '/SegmentPlugin/SubscriberConditionIdentity.php',
    'SegmentPlugin_SubscriberConditionListEntered' => $base . '/SegmentPlugin/SubscriberConditionListEntered.php',
    'SegmentPlugin_SubscriberConditionLists' => $base . '/SegmentPlugin/SubscriberConditionLists.php',
    'SegmentPlugin_ValueException' => $base . '/SegmentPlugin/ValueException.php',
    'phpList\plugin\SegmentPlugin\ControllerFactory' => $base . '/SegmentPlugin/ControllerFactory.php',
    'phpList\plugin\SegmentPlugin\Segment' => $base . '/SegmentPlugin/Segment.php',
    'phpList\plugin\SegmentPlugin\SelectedSubscribersExport' => $base . '/SegmentPlugin/SelectedSubscribersExport.php',
);
